---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install genometools -y
install:
  # Install Ansible.
  - pip install ansible

script:
  # We'll add some commands to test the role here.
#  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --tags test
